
work_dir: ./output/autsl_skeleton_bone_half

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /workspace/dataset/AUTSL/frames_skeleton/train_data_bone.npy
  label_path: /workspace/dataset/AUTSL/frames_skeleton/train_label.pkl
  debug: False

test_feeder_args:
  data_path: /workspace/dataset/AUTSL/frames_skeleton/val_data_bone.npy
  label_path: /workspace/dataset/AUTSL/frames_skeleton/val_label.pkl

# model
model: model.msg3d.Model
model_args:
  num_class: 226
  num_point: 54
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.autsl_rgb.AdjMatrixGraph

# optim
weight_decay: 0.0005
# weight_decay: 0.0003
base_lr: 0.1
# base_lr: 0.1
step: [80, 100]

# training
num_epoch: 120
# device: [0, 1]
device: [0, 1, 2, 3, 4, 5, 6, 7]
# batch_size: 32
batch_size: 256
# forward_batch_size: 32
forward_batch_size: 256
# test_batch_size: 32
test_batch_size: 256
nesterov: True




