
work_dir: ./work_dir/kinetics/msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: data/hand/train_data_joint.npy
  label_path: data/hand/train_label.pkl
  debug: False

test_feeder_args:
  # data_path: data/hand/val_data_joint.npy
  # label_path: data/hand/val_label.pkl
  data_path: data/hand/train_data_joint.npy
  label_path: data/hand/train_label.pkl

# model
model: model.msg3d.Model
model_args:
  num_class: 226
  num_point: 126
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  in_channels: 3
  graph: graph.autsl_face_68.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.25
# step: [60, 85]
policy:
  policy: 'step'
  warmup_ratio: 0.01
  warmup: 'linear'
  warmup_iters: 600
  step: [60, 85]

# training
num_epoch: 90
# device: [0, 1]
device: [0, 1, 2, 3]
batch_size: 96
# batch_size: 128
forward_batch_size: 96
# forward_batch_size: 64
test_batch_size: 96
# test_batch_size: 128
nesterov: True


